# Generated by Django 5.2.7 on 2025-10-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polygon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polygons',
            options={'verbose_name_plural': 'Polygons'},
        ),
    ]
